workflows:
  default:
    name: Default Workflow
    environment:
      vars:
        LANG: en_US.UTF-8
      xcode: latest
    triggers:
      - type: branch
        branchPatterns:
          - "main"
    actions:
      - name: Flutter Build Step
        script: |
          flutter pub get
          flutter build ios --release --no-codesign --build-dir=ios/build
          cd ios
          pod install
      - name: Archive & Distribute
        archive:
          scheme: Runner
          platform: iOS
          distributionMethod: app-store
          uploadSymbolication: true
          exportOptions:
            method: app-store
